AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ECRRepositoryURI:
    Type: String
    Description: The URI of the existing ECR repository

  ImageTag:
    Type: String
    Description: The tag of the image to use in ECS

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: The ID of an existing VPC

  Subnet:
    Type: String
    Description: The Id of an existing Subnet

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: fastapi-cluster  

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AWS::StackName}-task'
      Cpu: 256
      Memory: 512
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc  
      ExecutionRoleArn: arn:aws:iam::559651648870:role/LabRole
      ContainerDefinitions:
        - Name: fastapi-container
          Image: !Sub "${ECRRepositoryURI}:${ImageTag}"
          Memory: 512
          Cpu: 256
          PortMappings:
            - ContainerPort: 8000
              Protocol: tcp

  MyECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow inbound traffic on ports 8000 and 80"
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"  
          FromPort: 8000
          ToPort: 8000
          IpProtocol: tcp
        - CidrIp: "0.0.0.0/0"  
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp
      VpcId: !Ref VPC

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 2
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: [!Ref MyECSSecurityGroup] 
          Subnets: [!Ref Subnet]
