version: '3.8'

services:
  api-prod:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: my-api-prod
    container_name: api-prod
    ports:
      - "8000:8000"
    networks:
      - test-network

  api-test:
    build:
      context: .
      dockerfile: tests/Dockerfile
    image: my-api-test
    container_name: api-test
    depends_on:
      - api-prod
    volumes:
      - ./api:/api
    networks:
      - test-network

networks:
  test-network:
    driver: bridge