# Use the same base image
FROM python:3.9-slim

WORKDIR /tests

# Copy the requirements and install them
COPY ../requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app and test code
COPY ./tests .
COPY ./api /api
COPY .flake8 .flake8

# Set the command to run tests
CMD ["pytest"]