name: CI/CD Pipeline.

on:
  # Trigger the workflow on push
  push:
    branches:
      # Push events on master branch
      - main

jobs:
  Continuous-Integerate:
    # Define the OS in the workflow
    runs-on: ubuntu-latest 
    steps:
      # Check out repo so out workflow can access it
      - uses: actions/checkout@v2

      # Build and run the services with Docker Compose
      - name: Build and Run with Docker Compose
        run: docker-compose -f docker-compose.yml up --build --abort-on-container-exit

      # Lint production code with flake8 in api-prod
      - name: Lint Production Code
        run: docker-compose run --rm api-prod flake8

      # Lint test code with flake8 in api-test
      - name: Lint Test Code
        run: docker-compose run --rm api-test flake8

      # Optional: Tear down and clean up containers and networks
      - name: Clean up
        run: docker-compose down
